BEGIN;

ALTER TABLE phan_hoi ADD COLUMN IF NOT EXISTS phan_hoi_cua_nhan_vien text;
ALTER TABLE phan_hoi ADD COLUMN IF NOT EXISTS ngay_phan_hoi timestamptz;

CREATE TABLE IF NOT EXISTS thong_bao (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tai_khoan_id bigint NOT NULL REFERENCES tai_khoan(id) ON DELETE CASCADE,
  loai varchar(30) NOT NULL,
  tieu_de varchar(255) NOT NULL,
  noi_dung text NOT NULL,
  lien_ket varchar(100),
  da_doc boolean NOT NULL DEFAULT false,
  ngay_tao timestamptz NOT NULL DEFAULT now(),
  ngay_doc timestamptz,
  CONSTRAINT ck_thong_bao_noi_dung CHECK (length(trim(tieu_de)) > 0 AND length(trim(noi_dung)) > 0)
);

CREATE INDEX IF NOT EXISTS idx_thong_bao_tai_khoan ON thong_bao(tai_khoan_id,da_doc,ngay_tao DESC);

COMMIT;
