-- TẠO TOÀN BỘ CSDL CRM VÀ DỮ LIỆU DEMO
-- Chạy một lần trên database trống đã tạo. Không chạy lại các file 01..04.

-- CRM chuỗi trà sữa, cà phê. Chạy một lần trên database trống.
-- Sinh trực tiếp từ CRM_TraSua_CaPhe.dbml; không có DROP hoặc xóa dữ liệu.
BEGIN;
SET TIME ZONE 'Asia/Ho_Chi_Minh';
CREATE TYPE "vai_tro" AS ENUM (
  'admin',
  'manager',
  'staff',
  'customer'
);

CREATE TYPE "trang_thai_tai_khoan" AS ENUM (
  'active',
  'locked'
);

CREATE TYPE "gioi_tinh" AS ENUM (
  'nam',
  'nu',
  'khac',
  'khong_cung_cap'
);

CREATE TYPE "trang_thai_phan_hoi" AS ENUM (
  'moi',
  'da_xem',
  'da_tiep_thu'
);

CREATE TYPE "trang_thai_khao_sat" AS ENUM (
  'nhap',
  'dang_mo',
  'da_dong'
);

CREATE TABLE "chi_nhanh" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_chi_nhanh" varchar(20) UNIQUE NOT NULL,
  "ten_chi_nhanh" varchar(150) NOT NULL,
  "dia_chi" varchar(255) NOT NULL,
  "so_dien_thoai" varchar(20),
  "dang_hoat_dong" boolean NOT NULL DEFAULT true,
  CONSTRAINT "ck_chi_nhanh_ten" CHECK (length(trim(ten_chi_nhanh)) > 0)
);

CREATE TABLE "tai_khoan" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_dang_nhap" varchar(100) UNIQUE NOT NULL,
  "mat_khau_hash" varchar(255) NOT NULL,
  "vai_tro" vai_tro NOT NULL DEFAULT 'customer',
  "trang_thai" trang_thai_tai_khoan NOT NULL DEFAULT 'active',
  "chi_nhanh_id" bigint,
  "nguoi_tao_id" bigint,
  "ngay_tao" timestamptz NOT NULL DEFAULT (now()),
  "ngay_cap_nhat" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_tai_khoan_username" CHECK (length(trim(ten_dang_nhap)) >= 3),
  CONSTRAINT "ck_tai_khoan_hash" CHECK (length(mat_khau_hash) >= 20),
  CONSTRAINT "ck_khach_hang_toan_chuoi" CHECK (vai_tro <> 'customer' OR chi_nhanh_id IS NULL)
);

CREATE TABLE "nhom_so_thich" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ten_nhom" varchar(100) UNIQUE NOT NULL,
  "mo_ta" text,
  "dang_su_dung" boolean NOT NULL DEFAULT true,
  CONSTRAINT "ck_so_thich_ten" CHECK (length(trim(ten_nhom)) > 0)
);

CREATE TABLE "khach_hang" (
  "tai_khoan_id" bigint PRIMARY KEY NOT NULL,
  "ma_thanh_vien" varchar(30) UNIQUE NOT NULL,
  "ho_ten" varchar(150) NOT NULL,
  "nam_sinh" smallint NOT NULL,
  "gioi_tinh" gioi_tinh NOT NULL DEFAULT 'khong_cung_cap',
  "so_thich_id" bigint NOT NULL,
  "ngay_cap_nhat" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_khach_hang_ho_ten" CHECK (length(trim(ho_ten)) > 0),
  CONSTRAINT "ck_khach_hang_ma" CHECK (length(trim(ma_thanh_vien)) > 0),
  CONSTRAINT "ck_khach_hang_nam_sinh" CHECK (nam_sinh >= 1900)
);

CREATE TABLE "do_uong" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ma_do_uong" varchar(30) UNIQUE NOT NULL,
  "ten_do_uong" varchar(150) NOT NULL,
  "mo_ta" text,
  "dang_kinh_doanh" boolean NOT NULL DEFAULT true,
  "ngay_tao" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_do_uong_ten" CHECK (length(trim(ten_do_uong)) > 0)
);

CREATE TABLE "phan_hoi" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "khach_hang_id" bigint NOT NULL,
  "do_uong_id" bigint NOT NULL,
  "chi_nhanh_id" bigint,
  "so_sao" smallint NOT NULL,
  "noi_dung" text NOT NULL,
  "trang_thai" trang_thai_phan_hoi NOT NULL DEFAULT 'moi',
  "nguoi_xu_ly_id" bigint,
  "ngay_xu_ly" timestamptz,
  "ngay_gui" timestamptz NOT NULL DEFAULT (now()),
  CONSTRAINT "ck_phan_hoi_so_sao" CHECK (so_sao BETWEEN 1 AND 5),
  CONSTRAINT "ck_phan_hoi_noi_dung" CHECK (length(trim(noi_dung)) > 0),
  CONSTRAINT "ck_phan_hoi_xu_ly" CHECK ((trang_thai = 'moi' AND ngay_xu_ly IS NULL AND nguoi_xu_ly_id IS NULL) OR (trang_thai <> 'moi' AND ngay_xu_ly IS NOT NULL)),
  CONSTRAINT "ck_phan_hoi_thoi_gian" CHECK (ngay_xu_ly IS NULL OR ngay_xu_ly >= ngay_gui)
);

CREATE TABLE "khao_sat" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "tieu_de" varchar(255) NOT NULL,
  "mo_ta" text,
  "trang_thai" trang_thai_khao_sat NOT NULL DEFAULT 'nhap',
  "nguoi_tao_id" bigint NOT NULL,
  "ngay_tao" timestamptz NOT NULL DEFAULT (now()),
  "ngay_phat_hanh" timestamptz,
  "ngay_ket_thuc" timestamptz,
  CONSTRAINT "ck_khao_sat_tieu_de" CHECK (length(trim(tieu_de)) > 0),
  CONSTRAINT "ck_khao_sat_phat_hanh" CHECK ((trang_thai = 'nhap' AND ngay_phat_hanh IS NULL) OR (trang_thai <> 'nhap' AND ngay_phat_hanh IS NOT NULL)),
  CONSTRAINT "ck_khao_sat_thoi_gian" CHECK (ngay_ket_thuc IS NULL OR ngay_phat_hanh IS NULL OR ngay_ket_thuc > ngay_phat_hanh)
);

CREATE TABLE "cau_hoi" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "khao_sat_id" bigint NOT NULL,
  "noi_dung" text NOT NULL,
  "thu_tu" int NOT NULL,
  "bat_buoc" boolean NOT NULL DEFAULT true,
  CONSTRAINT "ck_cau_hoi_thu_tu" CHECK (thu_tu > 0),
  CONSTRAINT "ck_cau_hoi_noi_dung" CHECK (length(trim(noi_dung)) > 0)
);

CREATE TABLE "lua_chon" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "cau_hoi_id" bigint NOT NULL,
  "noi_dung" varchar(500) NOT NULL,
  "thu_tu" int NOT NULL,
  CONSTRAINT "ck_lua_chon_thu_tu" CHECK (thu_tu > 0),
  CONSTRAINT "ck_lua_chon_noi_dung" CHECK (length(trim(noi_dung)) > 0)
);

CREATE TABLE "phan_phoi_khao_sat" (
  "khao_sat_id" bigint NOT NULL,
  "khach_hang_id" bigint NOT NULL,
  "ngay_gui" timestamptz NOT NULL DEFAULT (now()),
  "ngay_hoan_thanh" timestamptz,
  CONSTRAINT "ck_phan_phoi_thoi_gian" CHECK (ngay_hoan_thanh IS NULL OR ngay_hoan_thanh >= ngay_gui),
  PRIMARY KEY ("khao_sat_id", "khach_hang_id")
);

CREATE TABLE "cau_tra_loi" (
  "khao_sat_id" bigint NOT NULL,
  "khach_hang_id" bigint NOT NULL,
  "cau_hoi_id" bigint NOT NULL,
  "lua_chon_id" bigint NOT NULL,
  PRIMARY KEY ("khao_sat_id", "khach_hang_id", "cau_hoi_id")
);

CREATE INDEX ON "tai_khoan" ("chi_nhanh_id");

CREATE INDEX ON "tai_khoan" ("vai_tro", "trang_thai");

CREATE INDEX ON "khach_hang" ("so_thich_id");

CREATE INDEX ON "khach_hang" ("nam_sinh");

CREATE INDEX ON "phan_hoi" ("trang_thai", "ngay_gui");

CREATE INDEX ON "phan_hoi" ("khach_hang_id", "ngay_gui");

CREATE INDEX ON "phan_hoi" ("do_uong_id", "ngay_gui");

CREATE INDEX ON "phan_hoi" ("chi_nhanh_id");

CREATE INDEX ON "khao_sat" ("nguoi_tao_id");

CREATE INDEX ON "khao_sat" ("trang_thai", "ngay_ket_thuc");

CREATE UNIQUE INDEX ON "cau_hoi" ("khao_sat_id", "thu_tu");

CREATE UNIQUE INDEX ON "cau_hoi" ("id", "khao_sat_id");

CREATE UNIQUE INDEX ON "lua_chon" ("cau_hoi_id", "thu_tu");

CREATE UNIQUE INDEX ON "lua_chon" ("id", "cau_hoi_id");

CREATE INDEX ON "phan_phoi_khao_sat" ("khach_hang_id", "ngay_hoan_thanh");

CREATE INDEX ON "cau_tra_loi" ("cau_hoi_id", "khao_sat_id");

CREATE INDEX ON "cau_tra_loi" ("lua_chon_id", "cau_hoi_id");

COMMENT ON TABLE "chi_nhanh" IS 'Danh mục chi nhánh; một khách hàng dùng chung tài khoản trên toàn chuỗi.';

COMMENT ON TABLE "tai_khoan" IS 'Tên đăng nhập được trigger chuyển thành chữ thường và bỏ khoảng trắng hai đầu. Vai trò dùng để phân quyền ở backend.';

COMMENT ON COLUMN "tai_khoan"."mat_khau_hash" IS 'Băm mật khẩu tại backend; không lưu mật khẩu gốc';

COMMENT ON COLUMN "tai_khoan"."chi_nhanh_id" IS 'Nơi làm việc của manager/staff; khách hàng để NULL';

COMMENT ON COLUMN "tai_khoan"."nguoi_tao_id" IS 'NULL khi tự đăng ký hoặc tạo admin ban đầu';

COMMENT ON TABLE "nhom_so_thich" IS 'Ví dụ: Trà sữa truyền thống; Cà phê muối; Trà trái cây nhiệt đới; Ít ngọt/Healthy. Đây là nhóm sở thích, không phải món cụ thể.';

COMMENT ON TABLE "khach_hang" IS 'Mỗi tài khoản customer có đúng một hồ sơ; kiểm tra cuối transaction. Mỗi khách có một sở thích mặc định theo đề.';

COMMENT ON COLUMN "khach_hang"."nam_sinh" IS 'Từ 1900 đến năm hiện tại; trigger kiểm tra cận trên';

COMMENT ON TABLE "do_uong" IS 'Danh mục để chọn khi phản hồi; chưa bao gồm đơn hàng, giá bán hoặc tồn kho.';

COMMENT ON COLUMN "phan_hoi"."chi_nhanh_id" IS 'NULL nếu khách phản hồi chung về sản phẩm';

COMMENT ON TABLE "khao_sat" IS 'Luồng trạng thái: nhap -> dang_mo -> da_dong. Hết hạn cũng chặn nộp dù chưa chuyển trạng thái. Khóa nội dung sau phát hành.';

COMMENT ON COLUMN "khao_sat"."ngay_ket_thuc" IS 'NULL nghĩa là chưa đặt hạn; vẫn có thể đóng thủ công';

COMMENT ON TABLE "cau_hoi" IS 'Mỗi câu là trắc nghiệm chọn một; tối thiểu hai lựa chọn khi phát hành.';

COMMENT ON TABLE "phan_phoi_khao_sat" IS 'Danh sách người nhận cố định tại lần phát hành. Khách đăng ký sau không tự được thêm. Khách bị khóa sau khi nhận vẫn nằm trong mẫu số.';

COMMENT ON COLUMN "phan_phoi_khao_sat"."ngay_hoan_thanh" IS 'NULL: chưa nộp; có giá trị: đã nộp. Không lưu nháp câu trả lời.';

COMMENT ON TABLE "cau_tra_loi" IS 'Ba khóa ngoại ghép bảo đảm đúng người nhận, đúng khảo sát và đúng đáp án của câu hỏi.';

ALTER TABLE "khach_hang" ADD FOREIGN KEY ("tai_khoan_id") REFERENCES "tai_khoan" ("id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tai_khoan" ADD FOREIGN KEY ("chi_nhanh_id") REFERENCES "chi_nhanh" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tai_khoan" ADD FOREIGN KEY ("nguoi_tao_id") REFERENCES "tai_khoan" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "khach_hang" ADD FOREIGN KEY ("so_thich_id") REFERENCES "nhom_so_thich" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phan_hoi" ADD FOREIGN KEY ("khach_hang_id") REFERENCES "khach_hang" ("tai_khoan_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phan_hoi" ADD FOREIGN KEY ("do_uong_id") REFERENCES "do_uong" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phan_hoi" ADD FOREIGN KEY ("chi_nhanh_id") REFERENCES "chi_nhanh" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phan_hoi" ADD FOREIGN KEY ("nguoi_xu_ly_id") REFERENCES "tai_khoan" ("id") ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "khao_sat" ADD FOREIGN KEY ("nguoi_tao_id") REFERENCES "tai_khoan" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cau_hoi" ADD FOREIGN KEY ("khao_sat_id") REFERENCES "khao_sat" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "lua_chon" ADD FOREIGN KEY ("cau_hoi_id") REFERENCES "cau_hoi" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phan_phoi_khao_sat" ADD FOREIGN KEY ("khao_sat_id") REFERENCES "khao_sat" ("id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "phan_phoi_khao_sat" ADD FOREIGN KEY ("khach_hang_id") REFERENCES "khach_hang" ("tai_khoan_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cau_tra_loi" ADD FOREIGN KEY ("khao_sat_id", "khach_hang_id") REFERENCES "phan_phoi_khao_sat" ("khao_sat_id", "khach_hang_id") ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cau_tra_loi" ADD FOREIGN KEY ("cau_hoi_id", "khao_sat_id") REFERENCES "cau_hoi" ("id", "khao_sat_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "cau_tra_loi" ADD FOREIGN KEY ("lua_chon_id", "cau_hoi_id") REFERENCES "lua_chon" ("id", "cau_hoi_id") ON DELETE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

COMMIT;


-- Chạy sau 01_schema.sql. Quy tắc liên bảng và các hàm nghiệp vụ.
-- p_nguoi_thuc_hien / p_khach_hang phải lấy từ phiên đăng nhập tại backend,
-- không lấy tùy ý từ body do người dùng gửi. Các hàm không thay thế xác thực API.
BEGIN;
SET TIME ZONE 'Asia/Ho_Chi_Minh';

CREATE FUNCTION fn_chuan_hoa_tai_khoan() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  NEW.ten_dang_nhap := lower(btrim(NEW.ten_dang_nhap));
  NEW.ngay_cap_nhat := clock_timestamp();
  RETURN NEW;
END $$;
CREATE TRIGGER trg_chuan_hoa_tai_khoan BEFORE INSERT OR UPDATE ON tai_khoan
FOR EACH ROW EXECUTE FUNCTION fn_chuan_hoa_tai_khoan();

CREATE FUNCTION fn_kiem_tra_khach_hang() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.nam_sinh > extract(year FROM current_date)::int THEN
    RAISE EXCEPTION 'Năm sinh không được lớn hơn năm hiện tại';
  END IF;
  NEW.ho_ten := btrim(NEW.ho_ten);
  NEW.ngay_cap_nhat := clock_timestamp();
  RETURN NEW;
END $$;
CREATE TRIGGER trg_kiem_tra_khach_hang BEFORE INSERT OR UPDATE ON khach_hang
FOR EACH ROW EXECUTE FUNCTION fn_kiem_tra_khach_hang();

-- Kiểm tra cuối transaction: customer có đúng một hồ sơ; nội bộ không có hồ sơ KH.
-- Nhờ trì hoãn đến COMMIT, đăng ký có thể INSERT tài khoản rồi INSERT hồ sơ.
CREATE FUNCTION fn_kiem_tra_ho_so() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE
  v_ids bigint[] := '{}';
  v_id bigint;
  v_vai_tro vai_tro;
  v_co_ho_so boolean;
BEGIN
  IF TG_TABLE_NAME = 'tai_khoan' THEN
    IF TG_OP <> 'INSERT' THEN v_ids := array_append(v_ids, OLD.id); END IF;
    IF TG_OP <> 'DELETE' THEN v_ids := array_append(v_ids, NEW.id); END IF;
  ELSE
    IF TG_OP <> 'INSERT' THEN v_ids := array_append(v_ids, OLD.tai_khoan_id); END IF;
    IF TG_OP <> 'DELETE' THEN v_ids := array_append(v_ids, NEW.tai_khoan_id); END IF;
  END IF;
  FOREACH v_id IN ARRAY v_ids LOOP
    SELECT vai_tro INTO v_vai_tro FROM tai_khoan WHERE id = v_id FOR SHARE;
    IF NOT FOUND THEN CONTINUE; END IF;
    SELECT EXISTS(SELECT 1 FROM khach_hang WHERE tai_khoan_id = v_id) INTO v_co_ho_so;
    IF (v_vai_tro = 'customer') <> v_co_ho_so THEN
      RAISE EXCEPTION 'Tài khoản %: vai trò customer và hồ sơ khách hàng phải khớp', v_id;
    END IF;
  END LOOP;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER trg_tai_khoan_ho_so AFTER INSERT OR UPDATE OR DELETE ON tai_khoan
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION fn_kiem_tra_ho_so();
CREATE CONSTRAINT TRIGGER trg_ho_so_tai_khoan AFTER INSERT OR UPDATE OR DELETE ON khach_hang
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION fn_kiem_tra_ho_so();

CREATE FUNCTION crm_kiem_tra_quyen(p_tai_khoan bigint, p_vai_tro vai_tro[])
RETURNS void LANGUAGE plpgsql AS $$
DECLARE v_tk tai_khoan%ROWTYPE;
BEGIN
  SELECT * INTO v_tk FROM tai_khoan WHERE id = p_tai_khoan FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Tài khoản không tồn tại'; END IF;
  IF v_tk.trang_thai <> 'active' THEN RAISE EXCEPTION 'Tài khoản đã bị khóa'; END IF;
  IF NOT (v_tk.vai_tro = ANY(p_vai_tro)) THEN RAISE EXCEPTION 'Không có quyền thực hiện'; END IF;
END $$;

CREATE FUNCTION fn_kiem_tra_phan_hoi() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    PERFORM crm_kiem_tra_quyen(NEW.khach_hang_id, ARRAY['customer']::vai_tro[]);
  ELSE
    IF ROW(NEW.khach_hang_id,NEW.do_uong_id,NEW.chi_nhanh_id,NEW.so_sao,NEW.noi_dung,NEW.ngay_gui)
       IS DISTINCT FROM ROW(OLD.khach_hang_id,OLD.do_uong_id,OLD.chi_nhanh_id,OLD.so_sao,OLD.noi_dung,OLD.ngay_gui) THEN
      RAISE EXCEPTION 'Không sửa nội dung phản hồi đã gửi';
    END IF;
  END IF;
  IF NEW.nguoi_xu_ly_id IS NOT NULL AND NOT EXISTS (
    SELECT 1 FROM tai_khoan WHERE id = NEW.nguoi_xu_ly_id AND vai_tro IN ('admin','manager','staff')
  ) THEN RAISE EXCEPTION 'Người xử lý phải là tài khoản nội bộ'; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_phan_hoi BEFORE INSERT OR UPDATE ON phan_hoi
FOR EACH ROW EXECUTE FUNCTION fn_kiem_tra_phan_hoi();

CREATE FUNCTION fn_bao_ve_khao_sat() RETURNS trigger LANGUAGE plpgsql AS $$
BEGIN
  IF TG_OP = 'INSERT' THEN
    IF NEW.trang_thai <> 'nhap' THEN RAISE EXCEPTION 'Khảo sát mới phải ở trạng thái nháp'; END IF;
  ELSE
    IF OLD.trang_thai <> 'nhap' AND ROW(NEW.id,NEW.tieu_de,NEW.mo_ta,NEW.nguoi_tao_id,NEW.ngay_phat_hanh,NEW.ngay_ket_thuc)
       IS DISTINCT FROM ROW(OLD.id,OLD.tieu_de,OLD.mo_ta,OLD.nguoi_tao_id,OLD.ngay_phat_hanh,OLD.ngay_ket_thuc) THEN
      RAISE EXCEPTION 'Nội dung và thời hạn đã cố định sau phát hành';
    END IF;
    IF NEW.trang_thai <> OLD.trang_thai AND NOT (
      (OLD.trang_thai = 'nhap' AND NEW.trang_thai = 'dang_mo') OR
      (OLD.trang_thai = 'dang_mo' AND NEW.trang_thai = 'da_dong')
    ) THEN RAISE EXCEPTION 'Chuyển trạng thái khảo sát không hợp lệ'; END IF;
    IF OLD.trang_thai = 'nhap' AND NEW.trang_thai = 'dang_mo' THEN
      IF NOT EXISTS(SELECT 1 FROM cau_hoi WHERE khao_sat_id = NEW.id) THEN
        RAISE EXCEPTION 'Khảo sát cần ít nhất một câu hỏi';
      END IF;
      IF EXISTS(SELECT 1 FROM cau_hoi c LEFT JOIN lua_chon l ON l.cau_hoi_id = c.id
        WHERE c.khao_sat_id = NEW.id GROUP BY c.id HAVING count(l.id) < 2) THEN
        RAISE EXCEPTION 'Mỗi câu hỏi cần ít nhất hai lựa chọn';
      END IF;
    END IF;
  END IF;
  IF TG_OP = 'INSERT' OR NEW.nguoi_tao_id IS DISTINCT FROM OLD.nguoi_tao_id THEN
    IF NOT EXISTS(SELECT 1 FROM tai_khoan WHERE id = NEW.nguoi_tao_id AND vai_tro IN ('admin','manager')) THEN
      RAISE EXCEPTION 'Người tạo khảo sát phải là admin hoặc manager';
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_bao_ve_khao_sat BEFORE INSERT OR UPDATE ON khao_sat
FOR EACH ROW EXECUTE FUNCTION fn_bao_ve_khao_sat();

-- Khóa hàng khảo sát để sửa cấu trúc và phát hành không chạy xen kẽ.
CREATE FUNCTION fn_bao_ve_cau_hoi() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_id bigint; v_trang_thai trang_thai_khao_sat;
BEGIN
  IF TG_OP = 'UPDATE' AND (NEW.id <> OLD.id OR NEW.khao_sat_id <> OLD.khao_sat_id) THEN
    RAISE EXCEPTION 'Không đổi ID hoặc chuyển câu hỏi sang khảo sát khác';
  END IF;
  IF TG_OP = 'DELETE' THEN v_id := OLD.khao_sat_id; ELSE v_id := NEW.khao_sat_id; END IF;
  SELECT trang_thai INTO v_trang_thai FROM khao_sat WHERE id = v_id FOR UPDATE;
  IF v_trang_thai <> 'nhap' THEN RAISE EXCEPTION 'Chỉ sửa câu hỏi khi khảo sát còn nháp'; END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_bao_ve_cau_hoi BEFORE INSERT OR UPDATE OR DELETE ON cau_hoi
FOR EACH ROW EXECUTE FUNCTION fn_bao_ve_cau_hoi();

CREATE FUNCTION fn_bao_ve_lua_chon() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_cau_hoi bigint; v_trang_thai trang_thai_khao_sat;
BEGIN
  IF TG_OP = 'UPDATE' AND (NEW.id <> OLD.id OR NEW.cau_hoi_id <> OLD.cau_hoi_id) THEN
    RAISE EXCEPTION 'Không đổi ID hoặc chuyển lựa chọn sang câu hỏi khác';
  END IF;
  IF TG_OP = 'DELETE' THEN v_cau_hoi := OLD.cau_hoi_id; ELSE v_cau_hoi := NEW.cau_hoi_id; END IF;
  SELECT k.trang_thai INTO v_trang_thai FROM khao_sat k
    JOIN cau_hoi c ON c.khao_sat_id = k.id WHERE c.id = v_cau_hoi FOR UPDATE OF k;
  IF v_trang_thai <> 'nhap' THEN RAISE EXCEPTION 'Chỉ sửa lựa chọn khi khảo sát còn nháp'; END IF;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_bao_ve_lua_chon BEFORE INSERT OR UPDATE OR DELETE ON lua_chon
FOR EACH ROW EXECUTE FUNCTION fn_bao_ve_lua_chon();

-- NULL danh sách: gửi toàn bộ khách active tại thời điểm phát hành.
-- Danh sách cụ thể: mọi ID phải là khách active; trùng ID trong input được loại bỏ.
CREATE FUNCTION crm_phat_hanh_khao_sat(p_nguoi_thuc_hien bigint, p_khao_sat bigint, p_khach_hang bigint[] DEFAULT NULL)
RETURNS integer LANGUAGE plpgsql AS $$
DECLARE v_ks khao_sat%ROWTYPE; v_so_luong int;
BEGIN
  PERFORM crm_kiem_tra_quyen(p_nguoi_thuc_hien, ARRAY['admin','manager']::vai_tro[]);
  SELECT * INTO v_ks FROM khao_sat WHERE id = p_khao_sat FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Khảo sát không tồn tại'; END IF;
  IF v_ks.trang_thai <> 'nhap' THEN RAISE EXCEPTION 'Khảo sát đã phát hành'; END IF;
  IF v_ks.ngay_ket_thuc IS NOT NULL AND v_ks.ngay_ket_thuc <= clock_timestamp() THEN
    RAISE EXCEPTION 'Thời hạn khảo sát đã qua';
  END IF;
  IF p_khach_hang IS NOT NULL AND EXISTS (
    SELECT 1 FROM unnest(p_khach_hang) x(id)
    WHERE NOT EXISTS(SELECT 1 FROM khach_hang h JOIN tai_khoan t ON t.id = h.tai_khoan_id
      WHERE h.tai_khoan_id = x.id AND t.trang_thai = 'active')
  ) THEN RAISE EXCEPTION 'Danh sách có khách hàng không tồn tại hoặc bị khóa'; END IF;
  UPDATE khao_sat SET trang_thai = 'dang_mo', ngay_phat_hanh = clock_timestamp() WHERE id = p_khao_sat;
  INSERT INTO phan_phoi_khao_sat(khao_sat_id,khach_hang_id,ngay_gui)
    SELECT p_khao_sat,h.tai_khoan_id,clock_timestamp()
    FROM khach_hang h JOIN tai_khoan t ON t.id = h.tai_khoan_id
    WHERE t.trang_thai = 'active' AND (p_khach_hang IS NULL OR h.tai_khoan_id = ANY(p_khach_hang));
  GET DIAGNOSTICS v_so_luong = ROW_COUNT;
  IF v_so_luong = 0 THEN RAISE EXCEPTION 'Không có người nhận; chưa phát hành khảo sát'; END IF;
  RETURN v_so_luong;
END $$;

-- Không lưu bài nháp. Mọi câu trả lời và trạng thái hoàn thành được ghi nguyên tử.
CREATE FUNCTION crm_nop_khao_sat(p_khach_hang bigint, p_khao_sat bigint, p_cau_tra_loi jsonb)
RETURNS void LANGUAGE plpgsql AS $$
DECLARE v_ks khao_sat%ROWTYPE; v_da_nop timestamptz;
BEGIN
  PERFORM crm_kiem_tra_quyen(p_khach_hang, ARRAY['customer']::vai_tro[]);
  SELECT * INTO v_ks FROM khao_sat WHERE id = p_khao_sat FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Khảo sát không tồn tại'; END IF;
  IF v_ks.trang_thai <> 'dang_mo' OR (v_ks.ngay_ket_thuc IS NOT NULL AND v_ks.ngay_ket_thuc <= clock_timestamp()) THEN
    RAISE EXCEPTION 'Khảo sát đã đóng hoặc hết hạn';
  END IF;
  SELECT ngay_hoan_thanh INTO v_da_nop FROM phan_phoi_khao_sat
    WHERE khao_sat_id = p_khao_sat AND khach_hang_id = p_khach_hang FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Khách hàng chưa được nhận khảo sát này'; END IF;
  IF v_da_nop IS NOT NULL THEN RAISE EXCEPTION 'Khảo sát đã hoàn thành; không được nộp lần hai'; END IF;
  IF p_cau_tra_loi IS NULL OR jsonb_typeof(p_cau_tra_loi) <> 'array' THEN
    RAISE EXCEPTION 'Câu trả lời phải là một mảng JSON';
  END IF;
  INSERT INTO cau_tra_loi(khao_sat_id,khach_hang_id,cau_hoi_id,lua_chon_id)
    SELECT p_khao_sat,p_khach_hang,x.cau_hoi_id,x.lua_chon_id
    FROM jsonb_to_recordset(p_cau_tra_loi) AS x(cau_hoi_id bigint,lua_chon_id bigint);
  -- FK ghép kiểm tra câu hỏi đúng khảo sát và lựa chọn đúng câu hỏi.
  -- PK ghép chặn lặp câu hỏi trong cùng bài.
  IF EXISTS(SELECT 1 FROM cau_hoi c WHERE c.khao_sat_id = p_khao_sat AND c.bat_buoc
    AND NOT EXISTS(SELECT 1 FROM cau_tra_loi a WHERE a.khao_sat_id = p_khao_sat
      AND a.khach_hang_id = p_khach_hang AND a.cau_hoi_id = c.id)) THEN
    RAISE EXCEPTION 'Chưa trả lời đủ các câu hỏi bắt buộc';
  END IF;
  UPDATE phan_phoi_khao_sat SET ngay_hoan_thanh = clock_timestamp()
    WHERE khao_sat_id = p_khao_sat AND khach_hang_id = p_khach_hang;
END $$;

CREATE FUNCTION crm_dong_khao_sat(p_nguoi_thuc_hien bigint, p_khao_sat bigint)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  PERFORM crm_kiem_tra_quyen(p_nguoi_thuc_hien, ARRAY['admin','manager']::vai_tro[]);
  UPDATE khao_sat SET trang_thai = 'da_dong' WHERE id = p_khao_sat AND trang_thai = 'dang_mo';
  IF NOT FOUND THEN RAISE EXCEPTION 'Không tìm thấy khảo sát đang mở'; END IF;
END $$;

CREATE FUNCTION crm_xu_ly_phan_hoi(p_nguoi_thuc_hien bigint, p_phan_hoi bigint, p_trang_thai trang_thai_phan_hoi)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  PERFORM crm_kiem_tra_quyen(p_nguoi_thuc_hien, ARRAY['admin','manager','staff']::vai_tro[]);
  IF p_trang_thai IS NULL OR p_trang_thai = 'moi' THEN RAISE EXCEPTION 'Chọn đã xem hoặc đã tiếp thu'; END IF;
  UPDATE phan_hoi SET trang_thai = p_trang_thai, nguoi_xu_ly_id = p_nguoi_thuc_hien, ngay_xu_ly = clock_timestamp()
    WHERE id = p_phan_hoi;
  IF NOT FOUND THEN RAISE EXCEPTION 'Phản hồi không tồn tại'; END IF;
END $$;

CREATE FUNCTION crm_dat_trang_thai_khach_hang(p_nguoi_thuc_hien bigint, p_khach_hang bigint, p_trang_thai trang_thai_tai_khoan)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  PERFORM crm_kiem_tra_quyen(p_nguoi_thuc_hien, ARRAY['admin','manager']::vai_tro[]);
  UPDATE tai_khoan SET trang_thai = p_trang_thai WHERE id = p_khach_hang AND vai_tro = 'customer';
  IF NOT FOUND THEN RAISE EXCEPTION 'Khách hàng không tồn tại'; END IF;
END $$;

CREATE FUNCTION crm_xoa_khach_hang(p_nguoi_thuc_hien bigint, p_khach_hang bigint)
RETURNS void LANGUAGE plpgsql AS $$
BEGIN
  PERFORM crm_kiem_tra_quyen(p_nguoi_thuc_hien, ARRAY['admin','manager']::vai_tro[]);
  DELETE FROM tai_khoan WHERE id = p_khach_hang AND vai_tro = 'customer';
  IF NOT FOUND THEN RAISE EXCEPTION 'Khách hàng không tồn tại'; END IF;
  -- CASCADE: hồ sơ, phản hồi, phân phối và câu trả lời của đúng khách đó.
  -- Cấu trúc khảo sát, món đồ uống, dữ liệu khách khác vẫn được giữ.
END $$;

-- Bảo vệ bài đã nộp, kể cả khi lập trình viên ghi trực tiếp vào bảng.
CREATE FUNCTION fn_bao_ve_cau_tra_loi() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_ks bigint; v_kh bigint; v_da_nop timestamptz;
BEGIN
  IF TG_OP = 'UPDATE' AND ROW(NEW.khao_sat_id,NEW.khach_hang_id,NEW.cau_hoi_id)
    IS DISTINCT FROM ROW(OLD.khao_sat_id,OLD.khach_hang_id,OLD.cau_hoi_id) THEN
    RAISE EXCEPTION 'Không đổi khóa của câu trả lời';
  END IF;
  IF TG_OP = 'DELETE' THEN v_ks:=OLD.khao_sat_id; v_kh:=OLD.khach_hang_id;
  ELSE v_ks:=NEW.khao_sat_id; v_kh:=NEW.khach_hang_id; END IF;
  SELECT ngay_hoan_thanh INTO v_da_nop FROM phan_phoi_khao_sat
    WHERE khao_sat_id=v_ks AND khach_hang_id=v_kh FOR UPDATE;
  -- Khi xóa khách hàng, hàng phân phối đã bị xóa trước khi CASCADE tới câu trả lời.
  IF FOUND AND v_da_nop IS NOT NULL THEN RAISE EXCEPTION 'Không sửa hoặc xóa câu trả lời đã nộp'; END IF;
  IF TG_OP='DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_bao_ve_cau_tra_loi BEFORE INSERT OR UPDATE OR DELETE ON cau_tra_loi
FOR EACH ROW EXECUTE FUNCTION fn_bao_ve_cau_tra_loi();

CREATE FUNCTION fn_bao_ve_phan_phoi() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_ks khao_sat%ROWTYPE;
BEGIN
  IF TG_OP='UPDATE' THEN
    IF ROW(NEW.khao_sat_id,NEW.khach_hang_id,NEW.ngay_gui)
       IS DISTINCT FROM ROW(OLD.khao_sat_id,OLD.khach_hang_id,OLD.ngay_gui) THEN
      RAISE EXCEPTION 'Không thay đổi người nhận hoặc ngày gửi';
    END IF;
    IF OLD.ngay_hoan_thanh IS NOT NULL AND NEW.ngay_hoan_thanh IS DISTINCT FROM OLD.ngay_hoan_thanh THEN
      RAISE EXCEPTION 'Không thay đổi trạng thái bài đã nộp';
    END IF;
  END IF;
  IF TG_OP='INSERT' OR (NEW.ngay_hoan_thanh IS NOT NULL AND OLD.ngay_hoan_thanh IS NULL) THEN
    PERFORM crm_kiem_tra_quyen(NEW.khach_hang_id,ARRAY['customer']::vai_tro[]);
    SELECT * INTO v_ks FROM khao_sat WHERE id=NEW.khao_sat_id FOR UPDATE;
    IF v_ks.trang_thai <> 'dang_mo' OR (v_ks.ngay_ket_thuc IS NOT NULL AND v_ks.ngay_ket_thuc<=clock_timestamp()) THEN
      RAISE EXCEPTION 'Khảo sát không còn mở';
    END IF;
  END IF;
  RETURN NEW;
END $$;
CREATE TRIGGER trg_bao_ve_phan_phoi BEFORE INSERT OR UPDATE ON phan_phoi_khao_sat
FOR EACH ROW EXECUTE FUNCTION fn_bao_ve_phan_phoi();

-- Cuối transaction: bài chưa nộp không được có câu trả lời; bài đã nộp đủ câu bắt buộc.
CREATE FUNCTION fn_kiem_tra_bai_lam() RETURNS trigger LANGUAGE plpgsql AS $$
DECLARE v_ks bigint; v_kh bigint; v_da_nop timestamptz;
BEGIN
  IF TG_OP='DELETE' THEN v_ks:=OLD.khao_sat_id; v_kh:=OLD.khach_hang_id;
  ELSE v_ks:=NEW.khao_sat_id; v_kh:=NEW.khach_hang_id; END IF;
  SELECT ngay_hoan_thanh INTO v_da_nop FROM phan_phoi_khao_sat
    WHERE khao_sat_id=v_ks AND khach_hang_id=v_kh;
  IF NOT FOUND THEN RETURN NULL; END IF;
  IF v_da_nop IS NULL THEN
    IF EXISTS(SELECT 1 FROM cau_tra_loi WHERE khao_sat_id=v_ks AND khach_hang_id=v_kh) THEN
      RAISE EXCEPTION 'Phải nộp toàn bộ bài trong cùng transaction, không lưu nháp';
    END IF;
  ELSIF EXISTS(SELECT 1 FROM cau_hoi c WHERE c.khao_sat_id=v_ks AND c.bat_buoc
    AND NOT EXISTS(SELECT 1 FROM cau_tra_loi a WHERE a.khao_sat_id=v_ks AND a.khach_hang_id=v_kh AND a.cau_hoi_id=c.id)) THEN
    RAISE EXCEPTION 'Bài đã nộp còn thiếu câu hỏi bắt buộc';
  END IF;
  RETURN NULL;
END $$;
CREATE CONSTRAINT TRIGGER trg_cau_tra_loi_day_du AFTER INSERT OR UPDATE OR DELETE ON cau_tra_loi
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION fn_kiem_tra_bai_lam();
CREATE CONSTRAINT TRIGGER trg_phan_phoi_day_du AFTER INSERT OR UPDATE OR DELETE ON phan_phoi_khao_sat
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW EXECUTE FUNCTION fn_kiem_tra_bai_lam();

COMMIT;


-- DỮ LIỆU GIẢ LẬP. Chạy một lần trên schema mới, sau 01 và 02.
-- Tất cả tài khoản demo dùng mật khẩu: DemoCRM@2026
-- Chuỗi hash scrypt: scrypt$N$r$p$salt_base64$derived_key_base64.
BEGIN;
SET TIME ZONE 'Asia/Ho_Chi_Minh';
INSERT INTO chi_nhanh(id,ma_chi_nhanh,ten_chi_nhanh,dia_chi) VALUES
(1,'CN01','Mộc Trà – Trung tâm','Địa chỉ demo số 1'),
(2,'CN02','Mộc Trà – Khu đại học','Địa chỉ demo số 2');
INSERT INTO nhom_so_thich(id,ten_nhom,mo_ta) VALUES
(1,'Trà sữa truyền thống','Thích vị trà sữa và topping'),
(2,'Cà phê muối','Thích cà phê kết hợp kem muối'),
(3,'Trà trái cây nhiệt đới','Thích trà kết hợp trái cây'),
(4,'Đồ uống ít ngọt/Healthy','Ưu tiên ít đường');
INSERT INTO tai_khoan(id,ten_dang_nhap,mat_khau_hash,vai_tro,chi_nhanh_id,nguoi_tao_id) VALUES
(1,'admin','scrypt$131072$8$1$DseiKUwzvqfeNvpiAhE6bg==$xCtv3TMoQPBF1PYcY7bcbs7wmQJroCqE8DfoNQAlLB0=','admin',NULL,NULL),
(2,'quanly','scrypt$131072$8$1$R7izVLcW4wvXhZMhK2IgDQ==$HPUrDCralz+H73eGlm5XyWbdxLcTY2dM9IFcHOxiqDk=','manager',1,1),
(3,'nhanvien','scrypt$131072$8$1$Sh0IYaMbY7KLdZUo91x9BQ==$zCj7J3VBZGO2nzZ6smfUHu0GpcnAIVbVqjFSp4HN7VA=','staff',1,1),
(4,'khach01','scrypt$131072$8$1$fUh0yzjKmh2m0fwU3Fr9Jg==$IsZ8qDnZddbvQJJxLvaDHynpKdAWUkDCosVyL8+W530=','customer',NULL,3),
(5,'khach02','scrypt$131072$8$1$bc9QI3lsAhzJTn6QKW/S6Q==$FfXPXpu2YI8Siy/zq5wt1qHkSXfd2i9vRv7SZm2T3o0=','customer',NULL,3),
(6,'khach03','scrypt$131072$8$1$pzv495gc6jAqgp4ARGecIQ==$AGPgH51Oau8heoO6TpUCdSqOmmJTnJ9pN8MtXO5U4yI=','customer',NULL,NULL),
(7,'khach04','scrypt$131072$8$1$C7/YjCXRSL61PI1hlsr/XA==$T1qfxcdMfeQJpbwBnlnKdsMzqmWB5YM0TdA2t0h4Kfg=','customer',NULL,NULL),
(8,'khach05','scrypt$131072$8$1$DYFgvn/vBxAY7eQ400eysg==$23mmdG99Gm4rY15O0JPPfDANrVEzyxWtFyAuJ2xDauQ=','customer',NULL,NULL),
(9,'khach06','scrypt$131072$8$1$oTBnsUhTzBbmEtDFnTBRug==$iyizd6AOPQiMr31LRIR0G0mKunwCWaRtodCJ28QmlE0=','customer',NULL,NULL),
(10,'khach07','scrypt$131072$8$1$QLYyHID5EswMsOQCDKGOmw==$23+oNcBrzv0WgAo5nYyRhskf3NIONsLRiy8XWSBrTrg=','customer',NULL,NULL),
(11,'khach08','scrypt$131072$8$1$1HYNxuK4eOBlWez5PMDOVw==$MLSbSPryFCPeuqqlj58L4YP5TwAk/GCkIB8y20Lx2uY=','customer',NULL,NULL);
INSERT INTO khach_hang(tai_khoan_id,ma_thanh_vien,ho_ten,nam_sinh,gioi_tinh,so_thich_id) VALUES
(4,'TV0004','Nguyễn Minh An',extract(year FROM current_date)::int-17,'nam',1),
(5,'TV0005','Trần Bảo Ngọc',extract(year FROM current_date)::int-20,'nu',1),
(6,'TV0006','Lê Hoàng Nam',extract(year FROM current_date)::int-24,'nam',2),
(7,'TV0007','Phạm Khánh Linh',extract(year FROM current_date)::int-28,'nu',3),
(8,'TV0008','Lê Gia Hân',extract(year FROM current_date)::int-35,'nu',4),
(9,'TV0009','Đỗ Quốc Bảo',extract(year FROM current_date)::int-42,'nam',2),
(10,'TV0010','Bùi Thanh Vy',extract(year FROM current_date)::int-18,'nu',3),
(11,'TV0011','Võ Đức Anh',extract(year FROM current_date)::int-31,'nam',4);
INSERT INTO do_uong(id,ma_do_uong,ten_do_uong,mo_ta,dang_kinh_doanh) VALUES
(1,'TS01','Trà sữa Oolong nướng','Trà Oolong, sữa và trân châu',true),
(2,'CP01','Cà phê muối','Cà phê cùng lớp kem muối',true),
(3,'TT01','Trà đào cam sả','Trà trái cây',true),
(4,'CB01','Cold Brew cam sả','Sản phẩm thử nghiệm',true),
(5,'HL01','Trà sen ít đường','Lựa chọn ít ngọt',true),
(6,'TS02','Trà sữa khoai môn','Đã ngừng kinh doanh, vẫn giữ lịch sử',false);
INSERT INTO phan_hoi(id,khach_hang_id,do_uong_id,chi_nhanh_id,so_sao,noi_dung,ngay_gui) VALUES
(1,4,1,1,4,'Trân châu mềm, trà hơi ngọt.',now()-interval '7 days'),
(2,5,1,2,5,'Mùi trà thơm, nhân viên tư vấn tốt.',now()-interval '6 days'),
(3,6,2,1,4,'Kem muối ngon, muốn vị cà phê đậm hơn.',now()-interval '5 days'),
(4,7,3,2,5,'Vị trái cây tươi, ít đá sẽ ngon hơn.',now()-interval '4 days'),
(5,8,5,1,5,'Mức đường phù hợp với sở thích.',now()-interval '3 days'),
(6,9,2,NULL,3,'Lớp kem hơi mặn so với khẩu vị.',now()-interval '2 days'),
(7,10,4,2,4,'Hương cam rõ, hậu vị cà phê dễ uống.',now()-interval '1 day'),
(8,11,6,1,2,'Lần trước đồ uống còn khá ngọt.',now()-interval '10 days');
SELECT crm_xu_ly_phan_hoi(3,1,'da_xem');
SELECT crm_xu_ly_phan_hoi(2,3,'da_tiep_thu');
SELECT crm_xu_ly_phan_hoi(2,8,'da_tiep_thu');
-- Khóa sau khi khách đã có phản hồi để minh họa lịch sử vẫn còn.
SELECT crm_dat_trang_thai_khach_hang(2,11,'locked');
INSERT INTO khao_sat(id,tieu_de,mo_ta,nguoi_tao_id,ngay_ket_thuc) VALUES
(1,'Khảo sát ra mắt Cold Brew Trái Cây','Chọn mức giá và loại quả yêu thích.',2,now()+interval '14 days'),
(2,'Khảo sát đồ uống ít ngọt','Thăm dò mức đường và lựa chọn mới.',2,now()+interval '7 days'),
(3,'Khảo sát trải nghiệm tại quán','Bản nháp để demo tạo và phát hành.',1,NULL);
INSERT INTO cau_hoi(id,khao_sat_id,noi_dung,thu_tu,bat_buoc) VALUES
(1,1,'Bạn sẵn sàng chi trả mức giá nào?',1,true),
(2,1,'Bạn thích Cold Brew kết hợp loại quả nào?',2,true),
(3,2,'Bạn thích mức đường nào?',1,true),
(4,2,'Bạn muốn thử đồ uống nào tiếp theo?',2,true),
(5,3,'Bạn đánh giá không gian quán thế nào?',1,true),
(6,3,'Bạn thường ghé quán vào thời điểm nào?',2,false);
INSERT INTO lua_chon(id,cau_hoi_id,noi_dung,thu_tu) VALUES
(1,1,'Từ 35.000 đến dưới 45.000 đồng',1),
(2,1,'Từ 45.000 đến 55.000 đồng',2),
(3,1,'Trên 55.000 đồng',3),
(4,2,'Cam sả',1),(5,2,'Vải',2),(6,2,'Mơ đào',3),
(7,3,'Không đường',1),(8,3,'30% đường',2),(9,3,'50% đường',3),
(10,4,'Trà sen ít đường',1),(11,4,'Cold Brew nguyên bản',2),(12,4,'Trà trái cây ít đường',3),
(13,5,'Rất thoải mái',1),(14,5,'Bình thường',2),(15,5,'Cần cải thiện',3),
(16,6,'Buổi sáng',1),(17,6,'Buổi chiều',2),(18,6,'Buổi tối',3);
SELECT crm_phat_hanh_khao_sat(2,1);
SELECT crm_nop_khao_sat(4,1,'[{"cau_hoi_id":1,"lua_chon_id":1},{"cau_hoi_id":2,"lua_chon_id":4}]');
SELECT crm_nop_khao_sat(5,1,'[{"cau_hoi_id":1,"lua_chon_id":2},{"cau_hoi_id":2,"lua_chon_id":4}]');
SELECT crm_nop_khao_sat(6,1,'[{"cau_hoi_id":1,"lua_chon_id":2},{"cau_hoi_id":2,"lua_chon_id":5}]');
SELECT crm_nop_khao_sat(7,1,'[{"cau_hoi_id":1,"lua_chon_id":3},{"cau_hoi_id":2,"lua_chon_id":6}]');
SELECT crm_phat_hanh_khao_sat(2,2,ARRAY[4,6,8]::bigint[]);
SELECT crm_nop_khao_sat(4,2,'[{"cau_hoi_id":3,"lua_chon_id":8},{"cau_hoi_id":4,"lua_chon_id":10}]');
SELECT crm_nop_khao_sat(6,2,'[{"cau_hoi_id":3,"lua_chon_id":7},{"cau_hoi_id":4,"lua_chon_id":11}]');
SELECT crm_dong_khao_sat(2,2);
-- Đồng bộ sequence sau khi chèn ID cụ thể, tránh trùng khóa khi thêm mới.
SELECT setval(pg_get_serial_sequence('chi_nhanh','id'),(SELECT max(id) FROM chi_nhanh),true);
SELECT setval(pg_get_serial_sequence('nhom_so_thich','id'),(SELECT max(id) FROM nhom_so_thich),true);
SELECT setval(pg_get_serial_sequence('tai_khoan','id'),(SELECT max(id) FROM tai_khoan),true);
SELECT setval(pg_get_serial_sequence('do_uong','id'),(SELECT max(id) FROM do_uong),true);
SELECT setval(pg_get_serial_sequence('phan_hoi','id'),(SELECT max(id) FROM phan_hoi),true);
SELECT setval(pg_get_serial_sequence('khao_sat','id'),(SELECT max(id) FROM khao_sat),true);
SELECT setval(pg_get_serial_sequence('cau_hoi','id'),(SELECT max(id) FROM cau_hoi),true);
SELECT setval(pg_get_serial_sequence('lua_chon','id'),(SELECT max(id) FROM lua_chon),true);
COMMIT;


-- Các VIEW chỉ đọc để cấp dữ liệu cho dashboard; chạy sau 01 và 02.
BEGIN;

CREATE VIEW v_danh_sach_khach_hang AS
SELECT h.tai_khoan_id,h.ma_thanh_vien,h.ho_ten,h.nam_sinh,
       extract(year FROM current_date)::int - h.nam_sinh AS tuoi_uoc_tinh,
       h.gioi_tinh,s.ten_nhom AS so_thich,t.ten_dang_nhap,t.trang_thai,t.ngay_tao
FROM khach_hang h JOIN tai_khoan t ON t.id = h.tai_khoan_id
JOIN nhom_so_thich s ON s.id = h.so_thich_id;

-- Mẫu số: tất cả hồ sơ KH hiện còn trong DB, gồm cả tài khoản locked.
-- Nhãn chỉ mô tả độ tuổi; không suy luận nghề nghiệp từ tuổi.
CREATE VIEW v_bao_cao_do_tuoi AS
WITH nhom(thu_tu,nhom_tuoi,tuoi_tu,tuoi_den) AS (
  VALUES (1,'Dưới 18',0,17),(2,'18–24',18,24),(3,'25–35',25,35),(4,'Trên 35',36,9999)
), tuoi AS (
  SELECT extract(year FROM current_date)::int - nam_sinh AS tuoi FROM khach_hang
)
SELECT n.thu_tu,n.nhom_tuoi,count(t.tuoi) AS so_khach_hang,
       round(100.0 * count(t.tuoi) / nullif((SELECT count(*) FROM tuoi),0),2) AS ty_le_phan_tram
FROM nhom n LEFT JOIN tuoi t ON t.tuoi BETWEEN n.tuoi_tu AND n.tuoi_den
GROUP BY n.thu_tu,n.nhom_tuoi;

CREATE VIEW v_bao_cao_so_thich AS
SELECT s.id,s.ten_nhom,count(h.tai_khoan_id) AS so_khach_hang,
       round(100.0 * count(h.tai_khoan_id) / nullif((SELECT count(*) FROM khach_hang),0),2) AS ty_le_phan_tram
FROM nhom_so_thich s LEFT JOIN khach_hang h ON h.so_thich_id = s.id
GROUP BY s.id,s.ten_nhom;

-- Đếm trên phân phối, không JOIN câu trả lời để tránh nhân số lượng người nhận.
CREATE VIEW v_tien_do_khao_sat AS
SELECT k.id AS khao_sat_id,k.tieu_de,k.trang_thai,k.ngay_ket_thuc,
       count(p.khach_hang_id) AS so_nguoi_duoc_gui,
       count(p.ngay_hoan_thanh) AS so_nguoi_da_lam,
       count(p.khach_hang_id) - count(p.ngay_hoan_thanh) AS so_nguoi_chua_lam,
       round(100.0 * count(p.ngay_hoan_thanh) / nullif(count(p.khach_hang_id),0),2) AS ty_le_hoan_thanh
FROM khao_sat k LEFT JOIN phan_phoi_khao_sat p ON p.khao_sat_id = k.id
GROUP BY k.id,k.tieu_de,k.trang_thai,k.ngay_ket_thuc;

-- Mẫu số từng câu: tổng câu trả lời của câu đó trong các bài đã nộp.
-- Câu không bắt buộc có thể có mẫu số nhỏ hơn tổng người hoàn thành.
-- Lựa chọn chưa được chọn vẫn xuất hiện, số lượt = 0.
CREATE VIEW v_ket_qua_khao_sat AS
WITH da_nop AS (
  SELECT a.* FROM cau_tra_loi a JOIN phan_phoi_khao_sat p
    ON p.khao_sat_id = a.khao_sat_id AND p.khach_hang_id = a.khach_hang_id
  WHERE p.ngay_hoan_thanh IS NOT NULL
), dem AS (
  SELECT c.khao_sat_id,c.id AS cau_hoi_id,c.noi_dung AS cau_hoi,c.thu_tu AS thu_tu_cau,
         l.id AS lua_chon_id,l.noi_dung AS lua_chon,l.thu_tu AS thu_tu_lua_chon,
         count(a.lua_chon_id) AS so_luot_chon
  FROM cau_hoi c JOIN lua_chon l ON l.cau_hoi_id = c.id
  LEFT JOIN da_nop a ON a.cau_hoi_id = c.id AND a.lua_chon_id = l.id
  GROUP BY c.khao_sat_id,c.id,c.noi_dung,c.thu_tu,l.id,l.noi_dung,l.thu_tu
)
SELECT *,sum(so_luot_chon) OVER (PARTITION BY cau_hoi_id) AS so_nguoi_tra_loi_cau,
       round(100.0 * so_luot_chon / nullif(sum(so_luot_chon) OVER (PARTITION BY cau_hoi_id),0),2) AS ty_le_phan_tram
FROM dem;

CREATE VIEW v_danh_gia_do_uong AS
SELECT d.id,d.ma_do_uong,d.ten_do_uong,count(p.id) AS so_phan_hoi,
       round(avg(p.so_sao),2) AS diem_trung_binh,
       count(p.id) FILTER (WHERE p.trang_thai = 'moi') AS so_phan_hoi_chua_xu_ly
FROM do_uong d LEFT JOIN phan_hoi p ON p.do_uong_id = d.id
GROUP BY d.id,d.ma_do_uong,d.ten_do_uong;

COMMIT;

-- Các truy vấn này chỉ đọc, có thể chạy trực tiếp trong pgAdmin.
SELECT * FROM v_bao_cao_do_tuoi ORDER BY thu_tu;
SELECT * FROM v_bao_cao_so_thich ORDER BY id;
SELECT * FROM v_tien_do_khao_sat ORDER BY khao_sat_id;
SELECT * FROM v_ket_qua_khao_sat ORDER BY khao_sat_id,thu_tu_cau,thu_tu_lua_chon;
SELECT * FROM v_danh_gia_do_uong ORDER BY id;
